//
// Created by jacko on 20/01/17.
//

#ifndef LWM2MEMBEDDED_LWM2MREGISTRATION_H
#define LWM2MEMBEDDED_LWM2MREGISTRATION_H

class LWM2MRegistration {

};


#endif //LWM2MEMBEDDED_LWM2MREGISTRATION_H
